name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout Shared Library
        uses: actions/checkout@v4
        with:
          repository: anilannamalair/my-shared-library
          path: shared-library

      - name: Say Hello
        run: ./shared-library/vars/sayHello.sh Anil

      - name: Install Maven Dependencies
        run: ./shared-library/vars/installMavenDependencies.sh

      - name: Build Project with Maven
        run: ./shared-library/vars/buildProjectWithMaven.sh

      - name: Run Tests with Maven
        run: ./shared-library/vars/runTestsWithMaven.sh
